# Titre (tel que dans le tableau) -> ticker Yahoo, place de cotation principale.
# KO : tickers sans cours sur Yahoo au 19.09.2026 (un seul yf.download groupé).
KO = {"B5A.DE", "VSCO"}
T = {
"A2 Milk":"ATM.NZ","AB Inbev":"ABI.BR","ADP":"ADP","AIRBUS":"AIR.PA","Air Liquide":"AI.PA","Alcon":"ALC.SW",
"Allianz":"ALV.DE","Alphabet (Google Cloud)":"GOOGL","Altria":"MO","AMG CRITICAL MATERIALS":"AMG.AS","Apple":"AAPL",
"Arcturus Therapeutics":"ARCT","Asmodee Group AB":"ASMDEE-B.ST","Assa Abloy":"ASSA-B.ST","Atmos Energy":"ATO",
"ATOSS SOFTWARE":"AOF.DE","Auto1 Group":"AG1.DE","Autolus Therapeutics":"AUTL","AXA":"CS.PA","Bachem":"BANB.SW",
"BAE Systems":"BA.L","BASF":"BAS.DE","Basilea Pharmaceutica":"BSLN.SW","Bauer":"B5A.DE","Bayer":"BAYN.DE",
"BB Biotech":"BION.SW","Beam Therapeutics":"BEAM","Befesa":"BFSA.DE","BE Semiconductor":"BESI.AS","BioNTech":"BNTX",
"Bloom Energy":"BE","Boeing":"BA","Booking Holdings":"BKNG","Boston Properties":"BXP","Boston Scientific":"BSX",
"BRAIN BIOTECH":"BNN.DE","Bristol-Myers Squibb":"BMY","Canadian National Railway":"CNR.TO","Canon":"7751.T",
"Carrefour":"CA.PA","Central Japan Railway":"9022.T","CEWE STIFTUNG":"CWC.DE","Cincinnati Financial":"CINF",
"Colruyt Group NV":"COLR.BR","Comet Holding":"COTN.SW","Consolidated Edison":"ED","COPT Defense Properties":"CDP",
"Cousins Properties":"CUZ","Cranswick":"CWK.L","Crispr Therapeutics":"CRSP","CrowdStrike":"CRWD","CTS Eventim":"EVD.DE",
"Daimler Truck":"DTG.DE","DBS Group":"D05.SI","Deere":"DE","Deutsche Bank":"DBK.DE","Deutsche Börse":"DB1.DE",
"Deutsche Telekom":"DTE.DE","Deutz":"DEZ.DE","Diebold Nixdorf":"DBD","DTE Energy":"DTE","East Japan Railway":"9020.T",
"Ecolab":"ECL","Entergy":"ETR","EOG Resources":"EOG","Equinor":"EQNR.OL","Essilor (später EssilorLuxottica)":"EL.PA",
"Euronext":"ENX.PA","Everest Group":"EG","ExxonMobil":"XOM","FactSet Research Systems":"FDS","Fastenal":"FAST",
"First Solar":"FSLR","Fresenius":"FRE.DE","Fresenius Medical Care":"FME.DE","Friedrich Vorwerk Group":"VH2.DE",
"Frontline":"FRO","Fuchs":"FPE3.DE","GEA Group":"G1A.DE","Gerresheimer":"GXI.DE","Gilead Sciences":"GILD","GTT":"GTT.PA",
"Halliburton":"HAL","Hensoldt":"HAG.DE","Hornbach Holding":"HBH.DE","Host Hotels and Resorts":"HST","Iberdrola":"IBE.MC",
"ICL Group":"ICL","Idexx Laboratories":"IDXX","Intellia Therapeutics":"NTLA","Intuitive Surgical":"ISRG","Ipsen":"IPN.PA",
"Iridium Communications":"IRDM","Iwatani":"8088.T","Jenoptik":"JEN.DE","Johnson & Johnson":"JNJ",
"Kawasaki Heavy Industries":"7012.T","KDDI":"9433.T","Kerry Group":"KRZ.IR","Kirin Holdings":"2503.T","KSB":"KSB3.DE",
"KWS Saat":"KWS.DE","Legend Biotech":"LEGN","Linde":"LIN","Lockheed Martin":"LMT","Logwin":"TGHN.DE","LVMH":"MC.PA",
"M1 Kliniken":"M12.DE","Marvell Technology Group":"MRVL","McCormick & Co.":"MKC","Merck & Co.":"MRK","Metlife":"MET",
"Metro":"MRU.TO","Mitsubishi UFJ Financial Group":"8306.T","Mitsui Fudosan":"8801.T","MLP":"MLP.DE",
"Münchener Rück":"MUV2.DE","MS & AD Insurance":"8725.T","M&T Bank":"MTB","MUNICH RE":"MUV2.DE","Munters Group":"MTRS.ST",
"Mutares":"MUX.DE","Nestlé":"NESN.SW","Netapp":"NTAP","Netflix":"NFLX","Next":"NXT.L","NextEra Energy":"NEE",
"Northrop Grumman":"NOC","Novartis":"NOVN.SW","NTT":"9432.T","Occidental Petroleum":"OXY","OC Oerlikon":"OERL.SW",
"Odakyu Electric Railway":"9007.T","Osaka Gas":"9532.T","Pernod Ricard":"RI.PA","Planoptik":"P4O.DE",
"PPG Industries":"PPG","PROLOGIS":"PLD","Publicis":"PUB.PA","RAIFFEISEN INTERNATIONAL":"RBI.VI","Reply SpA":"REY.MI",
"Resmed":"RMD","Rio Tinto":"RIO.L","Robinhood":"HOOD","Rolls-Royce":"RR.L","RPM International":"RPM","RWE":"RWE.DE",
"Sandvik":"SAND.ST","Sanofi":"SAN.PA","Santen":"4536.T","Schneider Electric":"SU.PA","Scout24":"G24.DE",
"Semperit":"SEM.VI","Shin-Etsu Chemical":"4063.T","Shionogi":"4507.T","Siemens":"SIE.DE","Siemens Energy":"ENR.DE",
"Singtel":"Z74.SI","SLB":"SLB","Snap-on":"SNA","SpaceX":"SPCX","Subsea 7":"SUBC.OL","Suncor Energy":"SU.TO",
"Sun Life Financial":"SLF.TO","Talanx":"TLX.DE","Teekay Tankers":"TNK","Thomson Reuters":"TRI.TO","Thyssenkrupp":"TKA.DE",
"Thyssenkrupp Marine Systems":"TKMS.DE","TKMS":"TKMS.DE","Thyssenkrupp/TKMS":"TKA.DE","Tonies":"TNIE.DE",
"Totalenergies":"TTE.PA","Traton":"8TRA.DE","Trimble":"TRMB","Tyler Technologies":"TYL","Umicore":"UMI.BR",
"Unilever PLC":"ULVR.L","Union Pacific":"UNP","Uniqa":"UQA.VI","United Health Group":"UNH","United Utilities":"UU.L",
"Urban Outfitters":"URBN","VAT Group":"VACN.SW","Veeva Systems":"VEEV","Veolia Environnement":"VIE.PA","Verizon":"VZ",
"Victoria's Secret":"VSCO","Viking Therapeutics":"VKTX","Vinci":"DG.PA","VIVENDI":"VIV.PA","Voestalpine":"VOE.VI",
"WEC Energy":"WEC","W&W":"WUW.DE","Zealand Pharma":"ZEAL.CO",
}
